import { postType } from './postType'
import { sponsoringPage } from './sponsoringPage'
import { teamMember } from './teamMember'
import { agendaType } from './agendaType'
import { homePage } from './homePage'
import { galleryType } from './galleryType'
import { gospelationPage } from './gospelationPage'
import { agendaPage } from './agendaPage'
import { teamPage } from './teamPage'
import gospelationEngagierenPage from './gospelationEngagierenPage'
import { threeImageSection } from './threeImageSection'
import gospelprojectPage from './gospelprojectPage'
import { gospelprojectMitmachenPage } from './gospelprojectMitmachenPage'
import { gospelprojectAnmeldungPage } from './gospelprojectAnmeldungPage'
import { gospelprojectTerminePage } from './gospelprojectTerminePage'
import { kontaktPage } from './kontaktPage'
import { gospelprojectMemberPage } from './gospelprojectMemberPage'
import { footerSettings } from './footerSettings'
import { navigationSettings } from './navigationSettings'
import { callToAction } from './callToAction'
import { gospelprojectBedingungenPage } from './gospelprojectBedingungenPage'
import { gospelvereinPage } from './gospelvereinPage'
import { newsletterPage } from './newsletterPage'
import { zusammenklangPage } from './zusammenklangPage'

export const schemaTypes = [postType, teamMember, agendaType, homePage, galleryType, gospelationPage, agendaPage, teamPage, gospelationEngagierenPage, threeImageSection, gospelprojectPage, gospelprojectMitmachenPage, gospelprojectAnmeldungPage, gospelprojectTerminePage, kontaktPage, gospelprojectMemberPage, footerSettings, navigationSettings, callToAction, sponsoringPage, gospelprojectBedingungenPage, gospelvereinPage, newsletterPage, zusammenklangPage]