import { postType } from './postType'
import { teamMember } from './teamMember'
import { agendaType } from './agendaType'
import { homePage } from './homePage'
import { galleryType } from './galleryType'
import { gospelationPage } from './gospelationPage'
import { agendaPage } from './agendaPage'
import { teamPage } from './teamPage'
import gospelationEngagierenPage from './gospelationEngagierenPage'
import { threeImageSection } from './threeImageSection'
import gospelprojectPage from './gospelprojectPage'
import { simplePage } from './simplePage'
import { gospelprojectMitmachenPage } from './gospelprojectMitmachenPage'
import { gospelprojectAnmeldungPage } from './gospelprojectAnmeldungPage'
import { gospelprojectTerminePage } from './gospelprojectTerminePage'
import { kontaktPage } from './kontaktPage'
import { gospelprojectMemberPage } from './gospelprojectMemberPage'
import { footerSettings } from './footerSettings'

export const schemaTypes = [postType, teamMember, agendaType, homePage, galleryType, gospelationPage, agendaPage, teamPage, gospelationEngagierenPage, threeImageSection, gospelprojectPage, simplePage, gospelprojectMitmachenPage, gospelprojectAnmeldungPage, gospelprojectTerminePage, kontaktPage, gospelprojectMemberPage, footerSettings]